#!/bin/python3
import turtle
import random
wn = turtle.Screen()
wn.bgcolor("lightgreen")
wn = turtle.Screen()
joke = turtle.Turtle()
joke.speed(10)
joke.color("Red")
joke.penup()
joke.goto(-10,150)
joke.pendown()
style=('fixedsys',30,'bold')
joke.write("Why was Pi feeling",font=style,align='center')
joke.penup()
joke.goto(0,50)
joke.color('blue')
style=('MSSansSarif',40)
joke.write('SAD?',font=style,align='center')
joke.penup()
joke.goto(0,-40)
image='CryingPi.png'
picture=turtle.Screen()
picture.addshape(image)
joke.shape(image)
youranswer=input('What do you think?')
if "His brother has been doing tau-ice as good" in youranswer:
  joke.hideturtle()
  joke.clear()
  wn.bgcolor("darkgreen")
  joke.color("LightBlue")
  style=('MSSerif',25,'bold')
  joke.goto(0,0)
  joke.write('CORRECT! Nice Job!',font=style,align='center')
  joke.goto(0,-100)
  joke.write('FULL ANSWER:',font=style,align='center')
  joke.speed(8)
  for i in range (0,2):
    joke.goto(-400,-400)
    joke.goto(-100,-100)
    joke.clear()
else: 
  joke.hideturtle()
  joke.clear()
  wn.bgcolor("red")
  joke.color("LightGreen")
  joke.goto(0,0)
  style=('Helvetica',20,'bold')
  joke.write('Sorry, that is incorrect!',font=style,align='center')
  joke.speed(8.5)
  for i in range (0,2):
    joke.goto(-400,-400)
    joke.goto(-100,-100)
    joke.clear()
    joke.goto(0,0)
  joke.write('THE ANSWER IS:',font=style,align='center')
  for i in range (0,2):
    joke.goto(-400,-400)
    joke.goto(-100,-100)
    joke.clear()
joke.speed(10)  
joke.hideturtle()
joke.clear()
wn.bgcolor("darkgreen")
joke.color("LightBlue")
joke.goto(-10,150)
style=('MSSerif',25,'bold')
joke.write('His Brother Has Been',font=style,align='center')
joke.color('yellow')
joke.goto(0,50)
style=('Helvetica',40)
joke.write('OUTSHINING',font=style,align='center')
joke.color('LightBlue')
joke.goto(0,-100)
style=('MSSerif',25,'bold')
joke.write('Him Recently...',font=style,align='center')
joke.speed=(4)
for i in range (0,2):
  joke.goto(-400,-400)
  joke.goto(-100,-100)
joke.clear()
joke.speed=(10)
joke.goto(0,100)
joke.write('He Has Been Doing',font=style,align='center')
joke.goto(0,0)
joke.color("LightPink")
style=('MSSansSarif',40,'bold')
joke.write('TAU-ice',font=style,align='center')
joke.goto(0,-100)
joke.color("LightBlue")
style=('MSSerif',25,'bold')
joke.write('As Good!',font=style,align='center')
joke.speed=(1)
joke.goto(400,400)
joke.goto(0,-175)
joke.speed=(10)
style=('Helvetica',20)
joke.color('red')
joke.write('Hahahahahahahahahahahahahahahahahah',font=style,align='center')